name: Bump Version
on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/

    - name: Install, Build and Test
      run: |
        npm ci
        npm run build
        npm test

    - name: Bump Version
      uses: phips28/gh-action-bump-version@v11.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        major-wording: "MAJOR,BREAKING CHANGE"
        minor-wording: "feat"
        patch-wording: "patch,fix,bugfix,chore"
        rc-wording: 'RELEASE,alpha'
        commit-message: 'CI: bumps version to {{version}}'